### ISSUE TITLE
mimeType field is empty

### ISSUE THREAD

**Issue by romovs** [lightbody/browsermob-proxy#286]
response.content.mimeType field isn't filled with the value of the Content-Type response header.

**Comment by jekh** [comment]
Thank you for noticing yet another HAR-related defect, @romovs. Like the redirectURL, this should (hopefully) be a quick fix.

What I should probably do is go through the HAR spec and make sure we have a test covering every field. I would suspect there are a few other missing fields as well.

**Comment by jekh** [comment]
This should be fixed now. Can you give it a try, @romovs?

**Comment by jekh** [comment]
Since this seems to be working, I'll close it. Feel free to reopen if you still experience any issues with beta-3. Thanks again for reporting this, @romovs!

**Comment by dirathea** [comment]
hi @jekh, Actually, I also still get this issue, and I'm using 2.1.0-beta-3.
My environment was I'm on corporate proxy, and I use CNTLM for authenticate it.
I'm using browsermobproxy like this : 
```java
 performanceProxy = new BrowserMobProxyServer(3123);
        HashMap<String, String> proxyConf = new HashMap<>();
        proxyConf.put("httpProxy", "127.0.0.1:3128");
        performanceProxy.setOptions(proxyConf);
```
