### ISSUE TITLE
can't add cookie to browser,how to it

### ISSUE THREAD

**Issue by WenRui13** [lightbody/browsermob-proxy#593]
my pom.xml file is configured like this:
![image](https://cloud.githubusercontent.com/assets/6370420/21765210/5a0b8658-d6a2-11e6-9b08-10fcfc6d2906.png)
and my test code is below:
    @Test
    public void test22() throws Exception {
        // start the proxy
        BrowserMobProxy proxy = new BrowserMobProxyServer();
        proxy.start(0);

        // get the Selenium proxy object
        Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);

        // configure it as a desired capability
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);

        // start the browser up
        WebDriver driver = new FirefoxDriver(capabilities);

        // set test url and cookie which is copied from browser.
        String testUrl = "http://prom.shop.jd.net/promotion/info/info2_queryActivitys.action?__vender_id=58725";
        final String cookieValue = "_vender_=XIS4VVGW4FROFQ65XGJM4LR3RSRO4XRPUXZD7O7OHWXJDNRA7JTNLKGYJKURVD3C4OITNULXAKEYBKJ2UMNZX66FR22\n" +
                "QMYERKDVREKJXXJBWKPKT4SLFZEHOLHETWBDTO2EU5D4U2RCWBIKND7PWTVEXBTL6JE6WIZYH5A6SJWBMYS3SX2F2VWNQQ63R2TK\n" +
                "SY4AZ4MENLFM4Y6ALKKKMQUAM5BNCXO3O5PLR5BVDKRHUXR2JUDYZ3J2CYB6TTITDGVYDRQZO22USJDLXGVTYZKENYV4HP2CNOTB\n" +
                "YZ2ZK2EPY6CYZQOVODDYM34HCDGZV4YTIMQQ2JDOXHIU33AEODJYSAH7NRQZTWQXF3QN6UJKHHFCUHK4HX24R2EUSNHUCBX3XF6YONJANORE3KEAW6BEX2F3CFU5FH533PBA\n" +
                "; Domain=.shop.jd.net; Path=/"; //登录后获取请求中cookie的那长串内容
        proxy.addRequestFilter(new RequestFilter() {
            @Override
            public HttpResponse filterRequest(HttpRequest request, HttpMessageContents contents, HttpMessageInfo messageInfo) {
                request.headers().add("Cookie", cookieValue);
                return null;
            }
        });
        driver.get(testUrl);
    }

when run it ,I have got the warning below:
2090 [main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: 0.0.0.0/0.0.0.0:0
2147 [main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
2300 [main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /0:0:0:0:0:0:0:0:51258
13272 [LittleProxy-0-ClientToProxyWorker-0] WARN net.lightbody.bmp.filters.BrowserMobHttpFilterChain - Filter in filter chain threw exception. Filter method may have been aborted.
java.lang.IllegalArgumentException: Only ' ' and '\t' are allowed after '\n': _vender_=XIS4VVGW4FROFQ65XGJM4LR3RSRO4XRPUXZD7O7OHWXJDNRA7JTNLKGYJKURVD3C4OITNULXAKEYBKJ2UMNZX66FR22
QMYERKDVREKJXXJBWKPKT4SLFZEHOLHETWBDTO2EU5D4U2RCWBIKND7PWTVEXBTL6JE6WIZYH5A6SJWBMYS3SX2F2VWNQQ63R2TK
SY4AZ4MENLFM4Y6ALKKKMQUAM5BNCXO3O5PLR5BVDKRHUXR2JUDYZ3J2CYB6TTITDGVYDRQZO22USJDLXGVTYZKENYV4HP2CNOTB
YZ2ZK2EPY6CYZQOVODDYM34HCDGZV4YTIMQQ2JDOXHIU33AEODJYSAH7NRQZTWQXF3QN6UJKHHFCUHK4HX24R2EUSNHUCBX3XF6YONJANORE3KEAW6BEX2F3CFU5FH533PBA
; Domain=.shop.jd.net; Path=/
	at io.netty.handler.codec.http.HttpHeaders.validateHeaderValue(HttpHeaders.java:1247)
	at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:106)
	at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:97)
	at PersonTest$2.filterRequest(PersonTest.java:365)
	at net.lightbody.bmp.filters.RequestFilterAdapter.clientToProxyRequest(RequestFilterAdapter.java:44)
	at net.lightbody.bmp.filters.BrowserMobHttpFilterChain.clientToProxyRequest(BrowserMobHttpFilterChain.java:65)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.doReadHTTPInitial(ClientToProxyConnection.java:227)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:191)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:80)
	at org.littleshoot.proxy.impl.ProxyConnection.readHTTP(ProxyConnection.java:135)
	at org.littleshoot.proxy.impl.ProxyConnection.read(ProxyConnection.java:120)
	at org.littleshoot.proxy.impl.ProxyConnection.channelRead0(ProxyConnection.java:587)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.littleshoot.proxy.impl.ProxyConnection$RequestReadMonitor.channelRead(ProxyConnection.java:715)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:372)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.littleshoot.proxy.impl.ProxyConnection$BytesReadMonitor.channelRead(ProxyConnection.java:692)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
13341 [LittleProxy-0-ClientToProxyWorker-1] WARN net.lightbody.bmp.filters.BrowserMobHttpFilterChain - Filter in filter chain threw exception. Filter method may have been aborted.
java.lang.IllegalArgumentException: Only ' ' and '\t' are allowed after '\n': _vender_=XIS4VVGW4FROFQ65XGJM4LR3RSRO4XRPUXZD7O7OHWXJDNRA7JTNLKGYJKURVD3C4OITNULXAKEYBKJ2UMNZX66FR22
QMYERKDVREKJXXJBWKPKT4SLFZEHOLHETWBDTO2EU5D4U2RCWBIKND7PWTVEXBTL6JE6WIZYH5A6SJWBMYS3SX2F2VWNQQ63R2TK
SY4AZ4MENLFM4Y6ALKKKMQUAM5BNCXO3O5PLR5BVDKRHUXR2JUDYZ3J2CYB6TTITDGVYDRQZO22USJDLXGVTYZKENYV4HP2CNOTB
YZ2ZK2EPY6CYZQOVODDYM34HCDGZV4YTIMQQ2JDOXHIU33AEODJYSAH7NRQZTWQXF3QN6UJKHHFCUHK4HX24R2EUSNHUCBX3XF6YONJANORE3KEAW6BEX2F3CFU5FH533PBA
; Domain=.shop.jd.net; Path=/
	at io.netty.handler.codec.http.HttpHeaders.validateHeaderValue(HttpHeaders.java:1247)
	at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:106)
	at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:97)
	at PersonTest$2.filterRequest(PersonTest.java:365)
	at net.lightbody.bmp.filters.RequestFilterAdapter.clientToProxyRequest(RequestFilterAdapter.java:44)
	at net.lightbody.bmp.filters.BrowserMobHttpFilterChain.clientToProxyRequest(BrowserMobHttpFilterChain.java:65)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.doReadHTTPInitial(ClientToProxyConnection.java:227)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:191)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:80)
	at org.littleshoot.proxy.impl.ProxyConnection.readHTTP(ProxyConnection.java:135)
	at org.littleshoot.proxy.impl.ProxyConnection.read(ProxyConnection.java:120)
	at org.littleshoot.proxy.impl.ProxyConnection.channelRead0(ProxyConnection.java:587)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.littleshoot.proxy.impl.ProxyConnection$RequestReadMonitor.channelRead(ProxyConnection.java:715)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.littleshoot.proxy.impl.ProxyConnection$BytesReadMonitor.channelRead(ProxyConnection.java:692)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
13372 [LittleProxy-JVM-shutdown-hook] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Shutting down proxy server immediately (non-graceful)
13372 [LittleProxy-JVM-shutdown-hook] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Closing all channels (non-graceful)

Can u help me? tks a lot.

**Comment by jekh** [comment]
First, you should be using a more recent version of BMP. See the main github page for usage information.

Regarding cookies, have a look at the error message. You have newlines in your cookie value, which is not allowed.

**Comment by WenRui13** [comment]
Tks, yes, I have corrected the cookie value, and set the version of BMP to 2.1.0-beta-6, but got new issue as below:
2881 [main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: 0.0.0.0/0.0.0.0:0
2962 [main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
3165 [main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /0:0:0:0:0:0:0:0:55368

===============================================
Custom suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================

19525 [LittleProxy-JVM-shutdown-hook] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Shutting down proxy server immediately (non-graceful)
19525 [LittleProxy-JVM-shutdown-hook] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Closing all channels (non-graceful)
19553 [LittleProxy-JVM-shutdown-hook] INFO org.littleshoot.proxy.impl.ServerGroup - Shutting down server group event loops (non-graceful)
19575 [LittleProxy-JVM-shutdown-hook] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Done shutting down proxy server

How to set my proxy? expecting your advice, best regards!

**Comment by jekh** [comment]
You're still not using the right version of BMP... Please read the docs, the information you need is right at the top.

**Comment by WenRui13** [comment]
tks a lot, I have solve this problem.

**Comment by Gintoki9851** [comment]
@WenRui13 How did you solve problem?
